services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FLASK_APP=${FLASK_APP}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - MYSQLDATABASE=${MYSQLDATABASE}
      - MYSQLHOST=mysql  # Nome do serviço do MySQL no Compose
      - MYSQLPORT=3306    # Porta do MySQL
      - MYSQLUSER=root
      - MYSQLPASSWORD=${MYSQLPASSWORD}  # Senha do usuário root
    depends_on:
      - mysql
    restart: always
    # deploy:  # Adicione aqui
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1  # alternativamente, use `count: all` para todas as GPUs
    #           capabilities: [gpu]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"  # Mapeia a porta 3307 do host para 3306 do contêiner
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLPASSWORD}  # Senha do usuário root
      MYSQL_DATABASE: ${MYSQLDATABASE}         # Nome do banco de dados a ser criado
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - "3306"

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: always
  #   ports:
  #     - "5006:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   command: --config.file=/etc/prometheus/prometheus.yml

volumes:
  mysql_data:
