"""user and alimentos

Revision ID: 7d2a02dbc190
Revises: b114ff49cdd6
Create Date: 2025-05-04 18:50:57.697430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2a02dbc190'
down_revision = 'b114ff49cdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clerk_key', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_clerk_key'), ['clerk_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_clerk_key'))
        batch_op.drop_column('clerk_key')

    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
