"""empty message

Revision ID: b114ff49cdd6
Revises: e0021b71e9ab
Create Date: 2025-04-28 19:11:49.957698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b114ff49cdd6'
down_revision = 'e0021b71e9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.drop_index('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alimento', schema=None) as batch_op:
        batch_op.create_index('nome', ['nome'], unique=True)

    # ### end Alembic commands ###
